// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW154QqRElpnlbTBwlFnuppO0RhQVMUDU',
    appId: '1:354278607313:web:7dc9811328d58b30b738f0',
    messagingSenderId: '354278607313',
    projectId: 'shotgun-48e08',
    authDomain: 'shotgun-48e08.firebaseapp.com',
    storageBucket: 'shotgun-48e08.firebasestorage.app',
    measurementId: 'G-28K1NBE46H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDk5d6ENQEpzYsOTSsjcwA7ZjmBBQIgWU',
    appId: '1:354278607313:android:200cf8dee4e41e25b738f0',
    messagingSenderId: '354278607313',
    projectId: 'shotgun-48e08',
    storageBucket: 'shotgun-48e08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ucrVV41WhDYSzaYCbUqs6bQ5u7WSYRc',
    appId: '1:354278607313:ios:38993c9af0390dd3b738f0',
    messagingSenderId: '354278607313',
    projectId: 'shotgun-48e08',
    storageBucket: 'shotgun-48e08.firebasestorage.app',
    iosBundleId: 'com.example.shotgun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4ucrVV41WhDYSzaYCbUqs6bQ5u7WSYRc',
    appId: '1:354278607313:ios:38993c9af0390dd3b738f0',
    messagingSenderId: '354278607313',
    projectId: 'shotgun-48e08',
    storageBucket: 'shotgun-48e08.firebasestorage.app',
    iosBundleId: 'com.example.shotgun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW154QqRElpnlbTBwlFnuppO0RhQVMUDU',
    appId: '1:354278607313:web:790a5fa546a8b456b738f0',
    messagingSenderId: '354278607313',
    projectId: 'shotgun-48e08',
    authDomain: 'shotgun-48e08.firebaseapp.com',
    storageBucket: 'shotgun-48e08.firebasestorage.app',
    measurementId: 'G-HY2Q89648R',
  );
}
